### ISSUE TITLE
Whenever i run the program i get the error "unrecognised content at end of stream"

### ISSUE THREAD

**Issue by Glitchblox** [GDColon/GD-Pixel-Art#17]
Error: unrecognised content at end of stream
    at SyncReader.process (C:\Users\username\Downloads\GD-Pixel-Art-master\node_modules\pngjs\lib\sync-reader.js:43:11)
    at module.exports (C:\Users\username\Downloads\GD-Pixel-Art-master\node_modules\pngjs\lib\parser-sync.js:68:10)
    at exports.read [as image/png] (C:\Users\username\Downloads\GD-Pixel-Art-master\node_modules\pngjs\lib\png-sync.js:7:10)
    at Jimp.parseBitmap (C:\Users\username\Downloads\GD-Pixel-Art-master\node_modules\@jimp\core\dist\utils\image-bitmap.js:157:52) {
  methodName: 'constructor'
}

**Comment by mangodev01** [comment]
your image is probably invalid
